# Generated by Django 6.1.1 on 2026-10-07 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_private_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='private_message',
            new_name='PrivateNote',
        ),
    ]
